services:
  fastapi:
    build: .
    container_name: whatsapp-fastapi
    env_file:
      - .env
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis

  worker:
    build: .
    container_name: whatsapp-worker
    env_file:
      - .env
    command: python worker.py
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: whatsapp-redis
    restart: unless-stopped